commands:
  discord:
    - "<blue><st>                                                             <reset>"
    - "<blue><bold>Join our Discord!"
    - "<yellow>https://discord.gg/wGKncuKFAw"
    - "<blue><st>                                                             <reset>"
  github:
    - "<yellow><st>                                                             <reset>"
    - "<yellow><bold>Check out our GitHub!"
    - "<gray>95% of our plugins are self made"
    - "<gray>and open source."
    - "<light_purple>https://github.com/Crumb-Network"
    - "<yellow><st>                                                             <reset>"

# List of plugins on our server
plugins:
  self-made:
    - "Crumb-Essentials"
  other:
    - "LuckPerms"